Removed blueprint and moved dependencies in `package.json`
ciena-frost/ember-frost-core pull request #423
Opened 2017-03-23 18:30 UTC by dafortin

**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

* **Removed** blueprint
* **Moved** dependencies in `package.json` dependencies

2017-04-03 18:11 UTC, sglanzer-fire requested changes
Would you mind adding some comments (inline) about the strategy being used here and where we're overriding the default Ember-CLI behaviour?

Also, I don't think the title of the PR is accurate anymore

2017-04-03 18:39 UTC, sandersky commented
For starters I see no tests around the new code. Look at how I did it [here](https://github.com/ciena-blueplanet/ember-test-utils/blob/master/package.json#L24).

2017-04-10 12:44 UTC, sglanzer commented on blueprints/ember-frost-core/index.js
> +    // Get the packages to install (not already installed) from a list of potential packages
Can we update this comment to add something like "Packages that are already installed in the consumer within the required semver range will not be re-installed or have blueprints re-run"?

Also might be worth noting this behaviour in the README - just a short blurb and point to the source (here)

2017-04-10 12:46 UTC, sglanzer commented on lib/utils/consumer.js
> +    return Object.assign(options.project.pkg.devDependencies, options.project.pkg.dependencies)
I'd add a null guard here just in case the path is empty

2017-04-10 12:47 UTC, sglanzer commented on lib/utils/npm.js
> +  _run: function (command, args = []) {
Are any of these available from `ember-cli` modules to borrow from?

2017-04-10 12:48 UTC, sglanzer commented on lib/utils/package-handler.js
> +      results.forEach(({pkg, result}) => {
Could run this in a reduce (no need to change, just noting)

2017-04-10 12:52 UTC, sglanzer commented on package.json
> +    "test-cli": "_mocha --recursive tests/unit/lib/"
What does the underscore on mocha do?

2017-04-10 12:53 UTC, sglanzer commented on tests/unit/lib/utils/npm.js
> +const npmModuleLocation = '../../../../lib/utils/npm'
Would an absolute path be easier here?

2017-04-10 12:59 UTC, sglanzer commented
I mainly care about the null guard and the _mocha comments, the rest are optional - nice work, I'm excited to see the improvements this brings

2017-04-10 13:03 UTC, dafortin commented on lib/utils/npm.js
> +  _run: function (command, args = []) {
We can run a command in `ember-cli` but we are not able to catch the output of the command. In the `view` case we need the output of the command.

2017-04-10 13:06 UTC, dafortin commented on tests/unit/lib/utils/npm.js
> +const npmModuleLocation = '../../../../lib/utils/npm'
I was having trouble with the absolute path for some obscure reason :(

2017-04-10 13:10 UTC, sglanzer commented on tests/unit/lib/utils/npm.js
> +const npmModuleLocation = '../../../../lib/utils/npm'
No problem, just curious

2017-04-10 13:11 UTC, dafortin commented on package.json
> +    "test-cli": "_mocha --recursive tests/unit/lib/"
https://github.com/gotwarlost/istanbul/issues/436

I changed it to mocha since we don't use istanbul.

2017-04-10 14:09 UTC, dafortin commented on blueprints/ember-frost-core/index.js
> +            saveDev: true
In `ember-cli@2.8` they remove the default behavior so we need to specify this.
https://github.com/ember-cli/ember-cli/issues/6318

They put the default behavior back in `ember-cli@2.11`

2017-04-10 14:10 UTC, dafortin commented
Handled all the PR comments.

2017-04-10 14:41 UTC, sglanzer-fire approved these changes

2017-04-10 14:42 UTC, sglanzer commented
@dafortin you mentioned you're hitting an issue with 2.8?  I assume that's blocking this?

2017-04-10 14:49 UTC, dafortin commented
No there is a workaround this issue: https://github.com/ciena-frost/ember-frost-core/pull/423/files#diff-f30e0028ce0a891ada9826aad7e7ade1R26

2017-04-10 17:06 UTC, merged